name: 🪲 Bug Report
description: Create a report to help us improve.
labels: [ bug ]
body:
  - type: checkboxes
    id: has_searched
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    id: is_related
    attributes:
      label: Are you sure that this bug is related to this DDEV Integration Plugin?
      description: |
        Please make sure that your problem is not related to [DDEV](https://github.com/drud/ddev). 
        An error message in your IDE is a clear indication that there is a bug in this DDEV integration plugin.
      options:
        - label: I am sure
  - type: input
    id: report_id
    attributes:
      label: Enter your error report id (If available)
      description: You will get an report id after submitting a error report in your IDE, related to this plugin.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        An error stack trace? Screenshots? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
