name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildPlugin --exclude-task test
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Assets
        uses: actions/upload-artifact@v4
        with:
          name: ddev-intellij-plugin
          path: build/distributions/*.zip
