# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildPlugin --exclude-task test

      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: ddev-intellij-plugin
          path: build/distributions/*.zip

  tests:
    runs-on: ubuntu-latest
#    runs-on: ${{ matrix.os }}
#      strategy:
#        matrix:
#          os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --info

      ##
      # Upload test reports
      ##
      - name: Upload HTML test reports
        uses: actions/upload-artifact@v2
        with:
          name: html-report-${{ matrix.os }}
          path: build/reports/tests/test

      - name: Upload XML test reports
        uses: actions/upload-artifact@v2
        with:
          name: xml-report-${{ matrix.os }}
          path: build/test-results/test
