name: Create Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-eap.*'
      - '[0-9]+.[0-9]+.[0-9]+-beta.*'
      - '[0-9]+.[0-9]+.[0-9]+-alpha.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract Changelog
        id: gradle-changelog
        run: ./gradlew getChangelog --quiet --no-header --console=plain > build/extracted_release_changelog.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'eap') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: build/extracted_release_changelog.md
