name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --stacktrace --info jacocoTestReport
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.os }}
          path: build/reports/tests/test

      - name: Upload HTML test coverage report
        if: ${{ matrix.os == 'ubuntu-latest' && always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
