name: Verify Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Verify Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runPluginVerifier --stacktrace --info
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.os }}
          path: build/reports/pluginVerifier/*/report.html
          if-no-files-found: error
